apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  unhealthyPodEvictionPolicy: AlwaysAllow
